name: flutter_web_dashboard
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  charts_flutter_new: ^0.12.0
  get: ^4.6.5
  data_table_2: ^2.5.6
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_core_web: ^2.10.0
  firebase_auth: ^4.15.3
  firebase_analytics: ^10.7.1
  cloud_firestore: ^4.13.6
  provider: ^6.0.1
  responsive_builder: 0.4.1
  image_picker: ^1.0.7
  firebase_storage: ^11.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/